name: JPL Accountants
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75037
title: JPL Accountants
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#080808'
    - '#a6a6a6'
    - '#38b1c5'
    - '#393939'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
