name: JPL Accountants
favicon: null
layout_spectrum: 0.4189
typography_spectrum: 0.51027
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#080808'
    - '#a6a6a6'
    - '#38b1c5'
    - '#393939'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
